import { invoke } from '@tauri-apps/api/core'
import { useReferencesStore } from '../../stores/references.js'

export async function ensureBibFile(texPath = '') {
  const normalizedPath = String(texPath || '').trim()
  if (!normalizedPath.includes('/')) return ''

  const referencesStore = useReferencesStore()
  const directory = normalizedPath.slice(0, normalizedPath.lastIndexOf('/'))
  const bibPath = `${directory}/references.bib`
  const content = referencesStore.exportBibTeX()
  const header =
    '% Auto-generated by Altals from project reference library\n% Do not edit manually - changes will be overwritten on next compile\n\n'

  await invoke('write_file', {
    path: bibPath,
    content: content.trim() ? `${header}${content}\n` : '% Auto-generated by Altals\n',
  })

  return bibPath
}
