export {
  classify,
  getViewerType,
  getFileIconName,
  getMimeType,
  isNewTab,
  isDraftPath,
  isPreviewPath,
  isMarkdownPreviewPath,
  previewSourcePathFromPath,
  isMarkdown,
  isLatex,
  isLatexEditorFile,
  isBibFile,
  isImage,
  isHtml,
  isMultimodalImage,
  isPdf,
  isBinaryFile,
  isRunnable,
  getLanguage,
  isRmdOrQmd,
  relativePath,
} from '../services/fileTypes.js'
